/** biome-ignore-all lint/style/useNamingConvention: Mirroring AssemblyScript internals. */

/**
 * Indicates the kind of am AssemblyScript node
 *
 * This mirrors AssemblyScript's NodeKind enum.
 */
export const NodeKind = {
	Assertion: 8,
	Binary: 9,
	Block: 31,
	Break: 32,
	Call: 10,
	Class: 11,
	ClassDeclaration: 52,
	Comma: 12,
	Comment: 67,
	Compiled: 30,
	Constructor: 27,
	Continue: 33,
	Decorator: 63,
	Do: 34,
	ElementAccess: 13,
	Empty: 35,
	EnumDeclaration: 53,
	EnumValueDeclaration: 54,
	Export: 36,
	ExportDefault: 37,
	ExportImport: 38,
	ExportMember: 64,
	Expression: 39,
	False: 14,
	FieldDeclaration: 55,
	For: 40,
	ForOf: 41,
	Function: 15,
	FunctionDeclaration: 56,
	FunctionType: 2,
	Identifier: 7,
	If: 42,
	Import: 43,
	ImportDeclaration: 57,
	IndexSignature: 66,
	InstanceOf: 16,
	InterfaceDeclaration: 58,
	Literal: 17,
	MethodDeclaration: 59,
	Module: 51,
	NamedType: 1,
	NamespaceDeclaration: 60,
	New: 18,
	Null: 19,
	Omitted: 20,
	Parameter: 6,
	Parenthesized: 21,
	PropertyAccess: 22,
	Return: 44,
	Source: 0,
	Super: 24,
	Switch: 45,
	SwitchCase: 65,
	Ternary: 23,
	This: 25,
	Throw: 46,
	True: 26,
	Try: 47,
	TupleType: 3,
	TypeDeclaration: 61,
	TypeName: 4,
	TypeParameter: 5,
	UnaryPostfix: 28,
	UnaryPrefix: 29,
	Variable: 48,
	VariableDeclaration: 62,
	Void: 49,
	While: 50,
} as const;

export type NodeKind = (typeof NodeKind)[keyof typeof NodeKind];
